create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'Administrator' check (role in ('Administrator', 'User')),
  company text not null default 'My Business',
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('sale', 'expense', 'purchase')),
  description text not null,
  amount numeric(14, 2) not null check (amount >= 0),
  category text not null,
  date date not null,
  reference text not null default '',
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  balance numeric(14, 2) not null default 0,
  last4 text not null
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(14, 2) not null,
  direction text not null check (direction in ('in', 'out')),
  date date not null,
  account text not null
);

create index if not exists transactions_user_id_idx on public.transactions(user_id);
create index if not exists transactions_date_idx on public.transactions(date desc);
create index if not exists transactions_type_idx on public.transactions(type);

alter table public.users disable row level security;
alter table public.transactions disable row level security;
alter table public.accounts disable row level security;
alter table public.activity disable row level security;
