import React,{useEffect,useState} from 'react';
import {Users,ShieldCheck,ArrowUpRight,ReceiptText,Pencil,Trash2,X,Save} from 'lucide-react';
import {api} from '../main';
import Panel from '../components/Panel';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const cards=[['Total users','users',Users,'bg-blue-50 text-blue-600'],['Transactions','transactions',ReceiptText,'bg-emerald-50 text-emerald-600'],['Revenue','revenue',ArrowUpRight,'bg-violet-50 text-violet-600'],['Expenses','expenses',ShieldCheck,'bg-red-50 text-red-600']];

export default function Admin({user:currentUser}){
 const [data,setData]=useState(null);
 const [editing,setEditing]=useState(null);
 const [saving,setSaving]=useState(false);
 const [error,setError]=useState('');
 const load=()=>api('/admin/overview').then(setData).catch(err=>setError(err.message));
 useEffect(load,[]);
 const changeRole=async(id,role)=>{try{await api(`/admin/users/${id}/role`,{method:'PUT',body:JSON.stringify({role})});load()}catch(err){setError(err.message)}};
 const saveUser=async event=>{event.preventDefault();setSaving(true);setError('');try{await api(`/admin/users/${editing.id}`,{method:'PUT',body:JSON.stringify(editing)});setEditing(null);await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
 const deleteUser=async target=>{if(!window.confirm(`Delete ${target.name}'s account? This cannot be undone.`))return;setError('');try{await api(`/admin/users/${target.id}`,{method:'DELETE'});await load()}catch(err){setError(err.message)}};
 if(error)return <div className="rounded-xl border border-red-100 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
 if(!data)return <div className="p-10 text-center text-sm text-slate-400">Loading admin workspace...</div>;
 return <div className="mx-auto max-w-[1400px] space-y-5 animate-in">
  <div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Administration</p><h1 className="mt-1 text-2xl font-bold">Control center</h1><p className="mt-1 text-sm text-slate-500">Manage people, access levels, and company-wide financial activity.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,key,Icon,tone])=><div key={key} className="rounded-xl border border-slate-100 bg-white p-5 shadow-card"><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={18}/></div><p className="mt-5 text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{key==='revenue'||key==='expenses'?money(data.stats[key]):data.stats[key]}</p></div>)}</div>
  <Panel title="Team access" subtitle={`${data.users.length} registered accounts`}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-[11px] uppercase tracking-wider text-slate-400"><th className="px-4 py-3">Member</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Role</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{data.users.map(member=><tr key={member.id} className="border-b border-slate-50 last:border-0"><td className="px-4 py-4"><p className="font-semibold">{member.name}</p><p className="text-xs text-slate-400">{member.email}</p></td><td className="px-4 py-4 text-slate-500">{member.company}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${member.role==='Administrator'?'bg-blue-50 text-blue-700':'bg-emerald-50 text-emerald-700'}`}>{member.role}</span></td><td className="px-4 py-4 text-right"><div className="flex justify-end gap-2"><select value={member.role} onChange={e=>changeRole(member.id,e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold"><option>Administrator</option><option>User</option></select><button title="Edit user" aria-label={`Edit ${member.name}`} onClick={()=>setEditing({...member})} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"><Pencil size={15}/></button><button title="Delete user" aria-label={`Delete ${member.name}`} disabled={member.id===currentUser?.id} onClick={()=>deleteUser(member)} className="grid h-9 w-9 place-items-center rounded-lg border border-rose-100 text-rose-600 hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-30"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></Panel>
  {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={saveUser} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Edit team member</h2><p className="mt-1 text-xs text-slate-500">Update account details and access.</p></div><button type="button" title="Close" aria-label="Close edit form" onClick={()=>setEditing(null)} className="text-slate-400 hover:text-slate-700"><X size={19}/></button></div><div className="mt-5 space-y-3">{[['name','Name'],['email','Email'],['company','Company']].map(([key,label])=><label key={key} className="block text-xs font-semibold text-slate-600">{label}<input required type={key==='email'?'email':'text'} value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-blue-500"/></label>)}<label className="block text-xs font-semibold text-slate-600">Role<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option>Administrator</option><option>User</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setEditing(null)} className="rounded-lg border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600">Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Save size={15}/>{saving?'Saving...':'Save changes'}</button></div></form></div>}
 </div>;
}
