import React,{useEffect,useState} from 'react';
import {BrainCircuit,ChevronDown,Download,FileSpreadsheet,FileText} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {api} from '../main';
import Panel from '../components/Panel';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const fileDate=()=>new Date().toISOString().slice(0,10);
const reportTitle=taxes=>taxes?'Tax Center Report':'Financial Report';
const reportRows=d=>[['Revenue',d.summary.revenue],['Expenses',d.summary.expenses],['Profit',d.summary.profit],['Taxable Income',d.summary.taxable]].map(([label,value])=>({label,value,formatted:money(value)}));
const download=(content,type,name)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};
const csvValue=value=>`"${String(value).replaceAll('"','""')}"`;
const colors=['#2563eb','#14b8a6','#f59e0b','#f43f5e','#8b5cf6','#64748b'];

function exportSpreadsheet(d,taxes,format){
 const rows=reportRows(d),title=reportTitle(taxes);
 if(format==='csv'){const csv=[[title,'Amount'],...rows.map(row=>[row.label,row.value])].map(row=>row.map(csvValue).join(',')).join('\n');download(csv,'text/csv;charset=utf-8',`${title.toLowerCase().replaceAll(' ','-')}-${fileDate()}.csv`);return}
 const table=`<table><thead><tr><th>Metric</th><th>Amount</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${row.label}</td><td>${row.value}</td></tr>`).join('')}</tbody></table>`;
 download(`<html><head><meta charset="utf-8"><title>${title}</title></head><body><h1>${title}</h1>${table}</body></html>`,'application/vnd.ms-excel',`${title.toLowerCase().replaceAll(' ','-')}-${fileDate()}.xls`);
}
function exportPdf(d,taxes){
 const rows=reportRows(d),title=reportTitle(taxes),reports=taxes?d.taxReports:d.reports,popup=window.open('','_blank','noopener,noreferrer');
 if(!popup){alert('Please allow pop-ups to export the PDF.');return}
 popup.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;color:#172033;padding:40px}table{border-collapse:collapse;width:100%;margin:24px 0}th,td{border:1px solid #dbe2ea;padding:10px;text-align:left}th{background:#eff6ff}td:last-child{text-align:right}.reports{display:grid;grid-template-columns:1fr 1fr;gap:12px}.report{border:1px solid #dbe2ea;padding:12px}.report small{color:#64748b}</style></head><body><h1>${title}</h1><p>Generated ${fileDate()}</p><table><thead><tr><th>Metric</th><th>Amount</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${row.label}</td><td>${row.formatted}</td></tr>`).join('')}</tbody></table><h2>${taxes?'Tax calculation summary':'Available reports'}</h2><div class="reports">${reports.map(report=>`<div class="report"><strong>${report.name}</strong><br><small>${report.period||report.description}</small></div>`).join('')}</div></body></html>`);popup.document.close();popup.focus();popup.print();
}
const tooltip={contentStyle:{borderRadius:8,border:'1px solid #e2e8f0',fontSize:12},formatter:value=>money(value)};

export default function Reports({taxes=false}){
 const [d,setD]=useState(null);const [open,setOpen]=useState(false);const [filter,setFilter]=useState({type:'year',year:String(new Date().getFullYear()),month:String(new Date().getMonth()+1).padStart(2,'0'),from:'01',to:'12'});
 useEffect(()=>{const query=filter.type==='month'?`?year=${filter.year}&month=${filter.month}`:filter.type==='range'?`?year=${filter.year}&from=${filter.from}&to=${filter.to}`:`?year=${filter.year}`;setD(null);api(`/reports${query}`).then(setD).catch(console.error)},[filter]);
 if(!d)return <div className="p-10 text-center text-sm text-slate-400">Loading reports...</div>;
 const rows=reportRows(d),margin=d.summary.revenue?d.summary.profit/d.summary.revenue*100:0;
 const analyst=margin>=30?'Strong profitability with healthy room to reinvest in growth.':margin>=10?'The business is profitable, but review recurring expenses to protect the margin.':'Profitability is under pressure; prioritize expense control and revenue collection.';
 const trend=d.trend.map(item=>({...item,label:new Date(`${item.month}-01T00:00:00`).toLocaleString('en-US',{month:'short'})}));
 return <div className="mx-auto max-w-[1400px] space-y-5">
  <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">{taxes?'Compliance':'Business intelligence'}</p><h1 className="mt-1 text-2xl font-bold">{taxes?'Tax Center':'Data Analyst'}</h1><p className="mt-1 text-sm text-slate-500">{taxes?'Prepare your tax figures and review liabilities.':'Understand performance through charts, trends, and detailed data.'}</p></div><div className="relative"><button onClick={()=>setOpen(!open)} aria-expanded={open} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-blue-700"><Download size={15}/>Export<ChevronDown size={14}/></button>{open&&<div className="absolute right-0 z-10 mt-2 w-48 rounded-lg border border-slate-100 bg-white p-1.5 shadow-lg"><button onClick={()=>{exportPdf(d,taxes);setOpen(false)}} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><FileText size={15}/>PDF / Print</button><button onClick={()=>{exportSpreadsheet(d,taxes,'xls');setOpen(false)}} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><FileSpreadsheet size={15}/>Excel (.xls)</button><button onClick={()=>{exportSpreadsheet(d,taxes,'csv');setOpen(false)}} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-xs font-semibold hover:bg-slate-50"><FileSpreadsheet size={15}/>CSV</button></div>}</div></div>
  <Panel title="Report period" subtitle={d.period}><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold text-slate-600">View<select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})} className="mt-1 block rounded-lg border px-3 py-2 text-xs font-semibold"><option value="year">Full year</option><option value="month">Specific month</option><option value="range">Month range</option></select></label><label className="text-xs font-semibold text-slate-600">Year<input type="number" value={filter.year} onChange={e=>setFilter({...filter,year:e.target.value})} className="mt-1 block w-24 rounded-lg border px-3 py-2 text-xs font-semibold"/></label>{filter.type==='month'&&<label className="text-xs font-semibold text-slate-600">Month<input type="number" min="1" max="12" value={Number(filter.month)} onChange={e=>setFilter({...filter,month:e.target.value.padStart(2,'0')})} className="mt-1 block w-24 rounded-lg border px-3 py-2 text-xs font-semibold"/></label>}{filter.type==='range'&&<><label className="text-xs font-semibold text-slate-600">From<input type="number" min="1" max="12" value={Number(filter.from)} onChange={e=>setFilter({...filter,from:e.target.value.padStart(2,'0')})} className="mt-1 block w-24 rounded-lg border px-3 py-2 text-xs font-semibold"/></label><label className="text-xs font-semibold text-slate-600">To<input type="number" min="1" max="12" value={Number(filter.to)} onChange={e=>setFilter({...filter,to:e.target.value.padStart(2,'0')})} className="mt-1 block w-24 rounded-lg border px-3 py-2 text-xs font-semibold"/></label></>}</div></Panel>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{rows.map(row=><div key={row.label} className="rounded-xl border border-slate-100 bg-white p-4 shadow-card"><p className="text-xs text-slate-500">{row.label}</p><p className="mt-2 text-xl font-bold text-slate-900">{row.formatted}</p></div>)}</div>
  <div className="grid gap-5 lg:grid-cols-[1.6fr_1fr]"><Panel title="Revenue vs expenses" subtitle="Monthly performance"><div className="h-72">{trend.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={value=>`$${Math.round(value/1000)}k`}/><Tooltip {...tooltip}/><Legend wrapperStyle={{fontSize:12}}/><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#2563eb" strokeWidth={3} dot={{r:3}}/><Line type="monotone" dataKey="expenses" name="Expenses" stroke="#f43f5e" strokeWidth={2} dot={{r:3}}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">No trend data for this period</div>}</div></Panel><Panel title="Expense mix" subtitle="By category"><div className="h-72">{d.breakdown.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={d.breakdown} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{d.breakdown.map((entry,index)=><Cell key={entry.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip {...tooltip}/><Legend layout="vertical" align="right" verticalAlign="middle" wrapperStyle={{fontSize:11}}/></PieChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">No expense data for this period</div>}</div></Panel></div>
  <Panel title="Income and expense comparison" subtitle="Grouped monthly totals"><div className="h-72">{trend.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={value=>`$${Math.round(value/1000)}k`}/><Tooltip {...tooltip}/><Legend wrapperStyle={{fontSize:12}}/><Bar dataKey="revenue" name="Revenue" fill="#14b8a6" radius={[4,4,0,0]}/><Bar dataKey="expenses" name="Expenses" fill="#f59e0b" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">No comparison data for this period</div>}</div></Panel>
  <Panel title="Transaction detail" subtitle={`${d.transactions.length} records in selected period`}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-wide text-slate-400"><th className="pb-3 pr-4">Date</th><th className="pb-3 pr-4">Description</th><th className="pb-3 pr-4">Category</th><th className="pb-3 pr-4">Type</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{d.transactions.map(tx=><tr key={tx.id} className="border-b border-slate-50 last:border-0"><td className="py-3 pr-4 text-slate-500">{tx.date}</td><td className="py-3 pr-4 font-semibold text-slate-800">{tx.description}</td><td className="py-3 pr-4 text-slate-500">{tx.category}</td><td className="py-3 pr-4 capitalize"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tx.type==='sale'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{tx.type}</span></td><td className="py-3 text-right font-bold text-slate-800">{money(tx.amount)}</td></tr>)}</tbody></table>{!d.transactions.length&&<p className="py-8 text-center text-sm text-slate-400">No transactions for this period</p>}</div></Panel>
  <Panel title="AI Data Analyst"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><BrainCircuit size={19}/></div><div><p className="text-sm font-semibold text-slate-800">{analyst}</p><p className="mt-1 text-xs text-slate-500">Profit margin for this period: {margin.toFixed(1)}%. Review the charts and transaction table above for the detail behind this insight.</p></div></div></Panel>
 </div>;
}
