import React,{useEffect,useState} from 'react';
import {CalendarClock,Download,FileText,ShieldCheck,ReceiptText,ArrowUpRight} from 'lucide-react';
import {api} from '../main';
import Panel from '../components/Panel';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
export default function Taxes(){
 const [data,setData]=useState(null);const [year,setYear]=useState(String(new Date().getFullYear()));
 useEffect(()=>{setData(null);api(`/reports?year=${year}`).then(setData).catch(console.error)},[year]);
 if(!data)return <div className="grid min-h-[500px] place-items-center text-sm text-slate-400">Loading tax workspace...</div>;
 const taxable=data.summary.taxable, estimated=taxable*.21, deductible=data.summary.expenses;
 return <div className="mx-auto max-w-[1400px] space-y-5">
  <div className="rounded-2xl bg-[#123b35] p-6 text-white shadow-xl shadow-emerald-950/10 sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-[#d8f36b] text-[#123b35]"><ShieldCheck size={21}/></div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8f36b]">Compliance workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight">Tax Center</h1><p className="mt-2 max-w-lg text-sm text-emerald-100">Keep taxable income, deductions, and filing milestones ready for review.</p></div><label className="text-xs font-semibold text-emerald-100">Tax year<select value={year} onChange={e=>setYear(e.target.value)} className="mt-2 block rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm font-bold text-white outline-none"><option className="text-slate-900">2026</option><option className="text-slate-900">2025</option><option className="text-slate-900">2024</option></select></label></div></div>
  <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-100 bg-white p-5 shadow-card"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Taxable income</p><p className="mt-2 text-2xl font-black">{money(taxable)}</p><p className="mt-2 text-xs text-slate-500">Revenue less eligible costs</p></div><div className="rounded-xl border border-slate-100 bg-white p-5 shadow-card"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Estimated liability</p><p className="mt-2 text-2xl font-black text-rose-600">{money(estimated)}</p><p className="mt-2 text-xs text-slate-500">Planning estimate at 21%</p></div><div className="rounded-xl border border-slate-100 bg-white p-5 shadow-card"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Deductible expenses</p><p className="mt-2 text-2xl font-black text-emerald-700">{money(deductible)}</p><p className="mt-2 text-xs text-slate-500">Purchases and operating costs</p></div></div>
  <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel title="Tax position" subtitle={`Reporting period: ${data.period}`}><div className="space-y-5"><div><div className="mb-2 flex justify-between text-xs font-semibold"><span className="text-slate-600">Taxable income</span><span>{money(taxable)}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#d8f36b]" style={{width:`${taxable?Math.min(100,Math.max(8,(taxable/(data.summary.revenue||1))*100)):8}%`}}/></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-emerald-50 p-4"><p className="text-xs font-semibold text-emerald-700">Revenue</p><p className="mt-1 text-lg font-black text-emerald-950">{money(data.summary.revenue)}</p></div><div className="rounded-lg bg-rose-50 p-4"><p className="text-xs font-semibold text-rose-700">Costs offsetting income</p><p className="mt-1 text-lg font-black text-rose-950">{money(data.summary.expenses)}</p></div></div></div></Panel><Panel title="Filing milestones" subtitle="Keep these dates on your calendar"><div className="space-y-3"><Milestone icon={CalendarClock} title="Quarterly estimate" date="September 15, 2026"/><Milestone icon={ReceiptText} title="Annual records review" date="January 31, 2027"/><Milestone icon={FileText} title="Tax filing target" date="April 15, 2027"/></div></Panel></div>
  <Panel title="Deductible categories" subtitle="Review source transactions before filing"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.breakdown.slice(0,4).map(item=><div key={item.name} className="flex items-center justify-between rounded-lg border border-slate-100 p-4"><div><p className="text-xs font-semibold text-slate-600">{item.name}</p><p className="mt-1 text-lg font-black">{money(item.value)}</p></div><ArrowUpRight size={16} className="text-emerald-600"/></div>)}</div>{!data.breakdown.length&&<p className="text-sm text-slate-400">No deductible transactions for this year.</p>}</Panel>
  <div className="flex justify-end"><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 shadow-sm hover:bg-slate-50"><Download size={15}/>Print tax summary</button></div>
 </div>;
}
function Milestone({icon:Icon,title,date}){return <div className="flex items-center gap-3 rounded-lg border border-slate-100 p-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-amber-50 text-amber-600"><Icon size={17}/></div><div><p className="text-xs font-bold text-slate-800">{title}</p><p className="mt-0.5 text-[11px] text-slate-400">{date}</p></div></div>}
