import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { DatabaseSync } from 'node:sqlite';
import path from 'path';
import {fileURLToPath} from 'url';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const db=new DatabaseSync(path.join(__dirname,'finance.db'));
const app=express();
app.use(cors());app.use(express.json());
const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';

db.exec('PRAGMA journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT DEFAULT 'Administrator',company TEXT DEFAULT 'My Business',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,description TEXT NOT NULL,amount REAL NOT NULL,category TEXT NOT NULL,date TEXT NOT NULL,reference TEXT,user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT NOT NULL,balance REAL NOT NULL,last4 TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT NOT NULL,amount REAL NOT NULL,direction TEXT NOT NULL,date TEXT NOT NULL,account TEXT NOT NULL);`);
const existing=db.prepare('SELECT id FROM users LIMIT 1').get();
if(!existing){const hash=bcrypt.hashSync('Admin@123',10);db.prepare('INSERT INTO users(name,email,password,role,company) VALUES(?,?,?,?,?)').run('Admin User','admin@example.com',hash,'Administrator','Acme Business');
 const tx=db.prepare('INSERT INTO transactions(type,description,amount,category,date,reference,user_id) VALUES(?,?,?,?,?,?,1)');
 const seed=[
 ['sale','Product sales',55200,'Sales','2026-08-05','INV-1001'],['sale','Service revenue',20340,'Other Income','2026-08-12','INV-1002'],['sale','Interest income',10000,'Interest Income','2026-08-21','BNK-201'],
 ['expense','Cost of goods sold',40250,'Cost of Goods Sold','2026-08-06','PO-3001'],['expense','Operating expenses',25600,'Operating Expenses','2026-08-14','EXP-4001'],['expense','Other expenses',10000,'Other Expenses','2026-08-25','EXP-4002'],
 ['purchase','Inventory purchase',18800,'Inventory','2026-08-04','PUR-5001'],['purchase','Office supplies',4300,'Supplies','2026-08-18','PUR-5002']];seed.forEach(x=>tx.run(...x));
 db.prepare('INSERT INTO accounts(name,type,balance,last4) VALUES(?,?,?,?)').run('Business Checking','Checking',82450,'4821');db.prepare('INSERT INTO accounts(name,type,balance,last4) VALUES(?,?,?,?)').run('Business Savings','Savings',43120,'7714');db.prepare('INSERT INTO accounts(name,type,balance,last4) VALUES(?,?,?,?)').run('Operations Card','Card',12580,'1192');
 const act=db.prepare('INSERT INTO activity(description,amount,direction,date,account) VALUES(?,?,?,?,?)');[['Customer payment',18500,'in','2026-08-28','Business Checking'],['Supplier payment',6200,'out','2026-08-27','Business Checking'],['Online sale',4250,'in','2026-08-26','Business Checking'],['Software subscription',890,'out','2026-08-24','Operations Card']].forEach(x=>act.run(...x));}

function auth(req,res,next){try{const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):'';req.user=jwt.verify(token,JWT_SECRET);next()}catch{return res.status(401).json({message:'Unauthorized'})}}
function requireAdmin(req,res,next){if(req.user.role!=='Administrator')return res.status(403).json({message:'Administrator access required'});next()}
function userSafe(u){return {id:u.id,name:u.name,email:u.email,role:u.role,company:u.company}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Smart Financial Management API'}));
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password,u.password))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.json({token,user:userSafe(u)})});
app.post('/api/auth/signup',(req,res)=>{const {name,email,password,company}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});if(password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});try{const hash=bcrypt.hashSync(password,10);const info=db.prepare("INSERT INTO users(name,email,password,role,company) VALUES(?,?,?,?,?)").run(name,email,hash,'User',company||'My Business');const u=db.prepare('SELECT * FROM users WHERE id=?').get(info.lastInsertRowid);const token=jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.status(201).json({token,user:userSafe(u)})}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({message:'An account with that email already exists'});throw err}});
app.get('/api/auth/profile',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);res.json({user:userSafe(u)})});
app.put('/api/auth/profile',auth,(req,res)=>{const {name,company}=req.body;db.prepare('UPDATE users SET name=?,company=? WHERE id=?').run(name,company,req.user.id);res.json({user:userSafe(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))})});
app.put('/api/auth/password',auth,(req,res)=>{const {currentPassword,newPassword}=req.body;if(!currentPassword||!newPassword)return res.status(400).json({message:'Both passwords are required'});if(newPassword.length<10)return res.status(400).json({message:'New password must be at least 10 characters'});const u=db.prepare('SELECT password FROM users WHERE id=?').get(req.user.id);if(!bcrypt.compareSync(currentPassword,u.password))return res.status(401).json({message:'Current password is incorrect'});db.prepare('UPDATE users SET password=? WHERE id=?').run(bcrypt.hashSync(newPassword,10),req.user.id);res.json({ok:true})});
app.get('/api/dashboard',auth,(req,res)=>{const rows=db.prepare("SELECT type, SUM(amount) total FROM transactions WHERE user_id=? GROUP BY type").all(req.user.id);const get=t=>rows.find(x=>x.type===t)?.total||0;const revenue=get('sale'),expenses=get('expense')+get('purchase'),profit=revenue-expenses;const trend=[['Jan',62000,45000],['Feb',88000,54000],['Mar',109000,62000],['Apr',92000,47000],['May',127000,76000],['Jun',109000,68000],['Jul',123000,79000],['Aug',129000,80000],['Sep',133000,83000],['Oct',128000,77000],['Nov',114000,67000],['Dec',123000,72000]].map(([month,r,e])=>({month,revenue:r,expenses:e,profit:r-e}));res.json({stats:{revenue,expenses,profit,margin:revenue?profit/revenue*100:0},income:[{name:'Sales',value:55200},{name:'Other Income',value:20340},{name:'Interest Income',value:10000}],expense:[{name:'Cost of Goods Sold',value:40250},{name:'Operating Expenses',value:25600},{name:'Other Expenses',value:10000}],trend})});
app.get('/api/transactions',auth,(req,res)=>{const type=req.query.type;const transactions=db.prepare('SELECT * FROM transactions WHERE user_id=? AND type=? ORDER BY date DESC,id DESC').all(req.user.id,type);res.json({transactions})});
app.post('/api/transactions',auth,(req,res)=>{const {type,description,amount,category,date,reference}=req.body;if(!type||!description||!amount||!category||!date)return res.status(400).json({message:'Missing required fields'});const info=db.prepare('INSERT INTO transactions(type,description,amount,category,date,reference,user_id) VALUES(?,?,?,?,?,?,?)').run(type,description,amount,category,date,reference||'',req.user.id);res.status(201).json({id:info.lastInsertRowid})});
app.put('/api/transactions/:id',auth,(req,res)=>{const {description,amount,category,date,reference}=req.body;if(!description||!amount||!category||!date)return res.status(400).json({message:'Missing required fields'});const result=db.prepare('UPDATE transactions SET description=?,amount=?,category=?,date=?,reference=? WHERE id=? AND user_id=?').run(description,amount,category,date,reference||'',req.params.id,req.user.id);if(!result.changes)return res.status(404).json({message:'Transaction not found'});res.json({ok:true})});
app.delete('/api/transactions/:id',auth,(req,res)=>{db.prepare('DELETE FROM transactions WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})});
app.get('/api/admin/overview',auth,requireAdmin,(req,res)=>{const users=db.prepare('SELECT id,name,email,role,company,created_at FROM users ORDER BY created_at DESC').all();const totals=db.prepare("SELECT COUNT(*) count,SUM(CASE WHEN type='sale' THEN amount ELSE 0 END) revenue,SUM(CASE WHEN type IN ('expense','purchase') THEN amount ELSE 0 END) expenses FROM transactions").get();res.json({users,stats:{users:users.length,transactions:totals.count||0,revenue:totals.revenue||0,expenses:totals.expenses||0}})});
app.put('/api/admin/users/:id/role',auth,requireAdmin,(req,res)=>{const role=req.body.role;if(!['Administrator','User'].includes(role))return res.status(400).json({message:'Invalid role'});db.prepare('UPDATE users SET role=? WHERE id=?').run(role,req.params.id);res.json({ok:true})});
app.put('/api/admin/users/:id',auth,requireAdmin,(req,res)=>{const {name,email,company,role}=req.body;if(!name?.trim()||!email?.trim()||!company?.trim()||!['Administrator','User'].includes(role))return res.status(400).json({message:'Name, email, company, and a valid role are required'});try{const result=db.prepare('UPDATE users SET name=?,email=?,company=?,role=? WHERE id=?').run(name.trim(),email.trim(),company.trim(),role,req.params.id);if(!result.changes)return res.status(404).json({message:'User not found'});res.json({user:userSafe(db.prepare('SELECT * FROM users WHERE id=?').get(req.params.id))})}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({message:'An account with that email already exists'});throw err}});
app.delete('/api/admin/users/:id',auth,requireAdmin,(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({message:'You cannot delete your own administrator account'});const target=db.prepare('SELECT id,role FROM users WHERE id=?').get(req.params.id);if(!target)return res.status(404).json({message:'User not found'});if(target.role==='Administrator'&&db.prepare("SELECT COUNT(*) count FROM users WHERE role='Administrator'").get().count<=1)return res.status(400).json({message:'At least one administrator account is required'});db.prepare('DELETE FROM users WHERE id=?').run(req.params.id);res.json({ok:true})});
app.get('/api/banking',auth,(req,res)=>res.json({accounts:db.prepare('SELECT * FROM accounts').all(),activity:db.prepare('SELECT * FROM activity ORDER BY date DESC,id DESC').all()}));
app.get('/api/reports',auth,(req,res)=>{const year=String(req.query.year||new Date().getFullYear()),month=String(req.query.month||'').padStart(2,'0'),from=String(req.query.from||''),to=String(req.query.to||'');let filter='user_id=?',params=[req.user.id],period=`${year}`;if(month&&month!=='00'){filter+=' AND substr(date,1,7)=?';params.push(`${year}-${month}`);period=new Date(`${year}-${month}-01T00:00:00`).toLocaleString('en-US',{month:'long',year:'numeric'})}else if(from&&to){filter+=' AND date>=? AND date<=?';params.push(`${year}-${from}-01`,`${year}-${to}-31`);period=`${year}-${from} to ${year}-${to}`}else{filter+=' AND substr(date,1,4)=?';params.push(year);period=`January — December ${year}`}const d=db.prepare(`SELECT SUM(CASE WHEN type='sale' THEN amount ELSE 0 END) revenue,SUM(CASE WHEN type IN ('expense','purchase') THEN amount ELSE 0 END) expenses FROM transactions WHERE ${filter}`).get(...params);const revenue=d.revenue||0,expenses=d.expenses||0;const trend=db.prepare(`SELECT substr(date,1,7) month,SUM(CASE WHEN type='sale' THEN amount ELSE 0 END) revenue,SUM(CASE WHEN type IN ('expense','purchase') THEN amount ELSE 0 END) expenses FROM transactions WHERE ${filter} GROUP BY substr(date,1,7) ORDER BY month`).all(...params);const breakdown=db.prepare(`SELECT category name,SUM(amount) value FROM transactions WHERE ${filter} AND type IN ('expense','purchase') GROUP BY category ORDER BY value DESC`).all(...params);const transactions=db.prepare(`SELECT id,date,description,category,type,amount,reference FROM transactions WHERE ${filter} ORDER BY date DESC,id DESC`).all(...params);res.json({period,summary:{revenue,expenses,profit:revenue-expenses,taxable:Math.max(0,revenue-expenses)},trend,breakdown,transactions,reports:[{name:'Profit & Loss Statement',period},{name:'Income Statement',period},{name:'Expense Analysis',period},{name:'Cash Flow Report',period}],taxReports:[{name:'Estimated Tax Summary',description:`Taxable income for ${period}`},{name:'Deductible Expenses',description:`Eligible costs for ${period}`},{name:'Tax Payment Schedule',description:'Upcoming obligations'},{name:'Annual Tax Report',description:'Year-end preparation'}]})});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Server error'})});
const port=Number(process.env.PORT||5000);app.listen(port,()=>console.log(`Smart Financial API running on http://localhost:${port}`));
