import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {createClient} from '@libsql/client';
import path from 'path';
import {existsSync} from 'fs';
import {fileURLToPath} from 'url';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const db=createClient({url:process.env.TURSO_DATABASE_URL||`file:${path.join(__dirname,'finance.db')}`,authToken:process.env.TURSO_AUTH_TOKEN});
const app=express();app.use(cors());app.use(express.json());
const secret=process.env.JWT_SECRET||'dev-secret-change-me';
const execute=(sql,args=[])=>db.execute({sql,args});
const all=async(sql,args=[])=>{const result=await execute(sql,args);return result.rows};
const one=async(sql,args=[])=>{const result=await all(sql,args);return result[0]};
const safe=user=>({id:user.id,name:user.name,email:user.email,role:user.role,company:user.company});
const issue=user=>({token:jwt.sign({id:user.id,email:user.email,role:user.role},secret,{expiresIn:'7d'}),user:safe(user)});
const auth=(req,res,next)=>{try{const header=req.headers.authorization||'';req.user=jwt.verify(header.startsWith('Bearer ')?header.slice(7):'',secret);next()}catch{return res.status(401).json({message:'Unauthorized'})}};
const admin=(req,res,next)=>req.user.role==='Administrator'?next():res.status(403).json({message:'Administrator access required'});

await db.batch([
 {sql:"CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT DEFAULT 'Administrator',company TEXT DEFAULT 'My Business',created_at TEXT DEFAULT CURRENT_TIMESTAMP)"},
 {sql:"CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,description TEXT NOT NULL,amount REAL NOT NULL,category TEXT NOT NULL,date TEXT NOT NULL,reference TEXT DEFAULT '',user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"},
 {sql:'CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT NOT NULL,balance REAL NOT NULL,last4 TEXT NOT NULL)'},
 {sql:"CREATE TABLE IF NOT EXISTS activity(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT NOT NULL,amount REAL NOT NULL,direction TEXT NOT NULL,date TEXT NOT NULL,account TEXT NOT NULL)"}
]);
if(!await one('SELECT id FROM users LIMIT 1')){
 const result=await execute('INSERT INTO users(name,email,password,role,company) VALUES(?,?,?,?,?)',['Admin User','admin@example.com',bcrypt.hashSync('Admin@123',10),'Administrator','Acme Business']);
 const userId=Number(result.lastInsertRowid);
 const seed=[['sale','Product sales',55200,'Sales','2026-08-05','INV-1001'],['sale','Service revenue',20340,'Other Income','2026-08-12','INV-1002'],['sale','Interest income',10000,'Interest Income','2026-08-21','BNK-201'],['expense','Cost of goods sold',40250,'Cost of Goods Sold','2026-08-06','PO-3001'],['expense','Operating expenses',25600,'Operating Expenses','2026-08-14','EXP-4001'],['expense','Other expenses',10000,'Other Expenses','2026-08-25','EXP-4002'],['purchase','Inventory purchase',18800,'Inventory','2026-08-04','PUR-5001'],['purchase','Office supplies',4300,'Supplies','2026-08-18','PUR-5002']];
 for(const item of seed)await execute('INSERT INTO transactions(type,description,amount,category,date,reference,user_id) VALUES(?,?,?,?,?,?,?)',[...item,userId]);
 for(const item of [['Business Checking','Checking',82450,'4821'],['Business Savings','Savings',43120,'7714'],['Operations Card','Card',12580,'1192']])await execute('INSERT INTO accounts(name,type,balance,last4) VALUES(?,?,?,?)',item);
 for(const item of [['Customer payment',18500,'in','2026-08-28','Business Checking'],['Supplier payment',6200,'out','2026-08-27','Business Checking'],['Online sale',4250,'in','2026-08-26','Business Checking'],['Software subscription',890,'out','2026-08-24','Operations Card']])await execute('INSERT INTO activity(description,amount,direction,date,account) VALUES(?,?,?,?,?)',item);
}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'Smart Financial Management API'}));
app.post('/api/auth/login',async(req,res,next)=>{try{const user=await one('SELECT * FROM users WHERE email=?',[req.body.email]);if(!user||!bcrypt.compareSync(req.body.password,user.password))return res.status(401).json({message:'Invalid email or password'});res.json(issue(user))}catch(error){next(error)}});
app.post('/api/auth/signup',async(req,res,next)=>{try{const {name,email,password,company}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});if(password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});const result=await execute('INSERT INTO users(name,email,password,role,company) VALUES(?,?,?,?,?)',[name,email,bcrypt.hashSync(password,10),'User',company||'My Business']);res.status(201).json(issue(await one('SELECT * FROM users WHERE id=?',[Number(result.lastInsertRowid)])))}catch(error){if(String(error.message).includes('UNIQUE'))return res.status(409).json({message:'An account with that email already exists'});next(error)}});
app.get('/api/auth/profile',auth,async(req,res,next)=>{try{res.json({user:safe(await one('SELECT * FROM users WHERE id=?',[req.user.id]))})}catch(error){next(error)}});
app.put('/api/auth/profile',auth,async(req,res,next)=>{try{await execute('UPDATE users SET name=?,company=? WHERE id=?',[req.body.name,req.body.company,req.user.id]);res.json({user:safe(await one('SELECT * FROM users WHERE id=?',[req.user.id]))})}catch(error){next(error)}});
app.put('/api/auth/password',auth,async(req,res,next)=>{try{const {currentPassword,newPassword}=req.body;const user=await one('SELECT password FROM users WHERE id=?',[req.user.id]);if(!currentPassword||!newPassword)return res.status(400).json({message:'Both passwords are required'});if(newPassword.length<10)return res.status(400).json({message:'New password must be at least 10 characters'});if(!bcrypt.compareSync(currentPassword,user.password))return res.status(401).json({message:'Current password is incorrect'});await execute('UPDATE users SET password=? WHERE id=?',[bcrypt.hashSync(newPassword,10),req.user.id]);res.json({ok:true})}catch(error){next(error)}});
app.get('/api/dashboard',auth,async(req,res,next)=>{try{const values=await all('SELECT type,SUM(amount) total FROM transactions WHERE user_id=? GROUP BY type',[req.user.id]);const get=type=>Number(values.find(value=>value.type===type)?.total||0),revenue=get('sale'),expenses=get('expense')+get('purchase');res.json({stats:{revenue,expenses,profit:revenue-expenses,margin:revenue?((revenue-expenses)/revenue)*100:0},income:[],expense:[],trend:[]})}catch(error){next(error)}});
app.get('/api/transactions',auth,async(req,res,next)=>{try{res.json({transactions:await all('SELECT * FROM transactions WHERE user_id=? AND type=? ORDER BY date DESC,id DESC',[req.user.id,req.query.type])})}catch(error){next(error)}});
app.post('/api/transactions',auth,async(req,res,next)=>{try{const {type,description,amount,category,date,reference}=req.body;if(!type||!description||!amount||!category||!date)return res.status(400).json({message:'Missing required fields'});const result=await execute('INSERT INTO transactions(type,description,amount,category,date,reference,user_id) VALUES(?,?,?,?,?,?,?)',[type,description,amount,category,date,reference||'',req.user.id]);res.status(201).json({id:Number(result.lastInsertRowid)})}catch(error){next(error)}});
app.put('/api/transactions/:id',auth,async(req,res,next)=>{try{const {description,amount,category,date,reference}=req.body;if(!description||!amount||!category||!date)return res.status(400).json({message:'Missing required fields'});const result=await execute('UPDATE transactions SET description=?,amount=?,category=?,date=?,reference=? WHERE id=? AND user_id=?',[description,amount,category,date,reference||'',req.params.id,req.user.id]);if(!result.rowsAffected)return res.status(404).json({message:'Transaction not found'});res.json({ok:true})}catch(error){next(error)}});
app.delete('/api/transactions/:id',auth,async(req,res,next)=>{try{await execute('DELETE FROM transactions WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({ok:true})}catch(error){next(error)}});
app.get('/api/admin/overview',auth,admin,async(req,res,next)=>{try{const users=await all('SELECT id,name,email,role,company,created_at FROM users ORDER BY created_at DESC'),totals=await one("SELECT COUNT(*) count,SUM(CASE WHEN type='sale' THEN amount ELSE 0 END) revenue,SUM(CASE WHEN type IN ('expense','purchase') THEN amount ELSE 0 END) expenses FROM transactions");res.json({users,stats:{users:users.length,transactions:Number(totals.count||0),revenue:Number(totals.revenue||0),expenses:Number(totals.expenses||0)}})}catch(error){next(error)}});
app.put('/api/admin/users/:id/role',auth,admin,async(req,res,next)=>{try{if(!['Administrator','User'].includes(req.body.role))return res.status(400).json({message:'Invalid role'});await execute('UPDATE users SET role=? WHERE id=?',[req.body.role,req.params.id]);res.json({ok:true})}catch(error){next(error)}});
app.put('/api/admin/users/:id',auth,admin,async(req,res,next)=>{try{const {name,email,company,role}=req.body;if(!name?.trim()||!email?.trim()||!company?.trim()||!['Administrator','User'].includes(role))return res.status(400).json({message:'Name, email, company, and a valid role are required'});const result=await execute('UPDATE users SET name=?,email=?,company=?,role=? WHERE id=?',[name.trim(),email.trim(),company.trim(),role,req.params.id]);if(!result.rowsAffected)return res.status(404).json({message:'User not found'});res.json({user:safe(await one('SELECT * FROM users WHERE id=?',[req.params.id]))})}catch(error){if(String(error.message).includes('UNIQUE'))return res.status(409).json({message:'An account with that email already exists'});next(error)}});
app.delete('/api/admin/users/:id',auth,admin,async(req,res,next)=>{try{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({message:'You cannot delete your own administrator account'});const target=await one('SELECT id,role FROM users WHERE id=?',[req.params.id]);if(!target)return res.status(404).json({message:'User not found'});const count=await one("SELECT COUNT(*) count FROM users WHERE role='Administrator'");if(target.role==='Administrator'&&Number(count.count)<=1)return res.status(400).json({message:'At least one administrator account is required'});await execute('DELETE FROM users WHERE id=?',[req.params.id]);res.json({ok:true})}catch(error){next(error)}});
app.get('/api/banking',auth,async(req,res,next)=>{try{res.json({accounts:await all('SELECT * FROM accounts'),activity:await all('SELECT * FROM activity ORDER BY date DESC,id DESC')})}catch(error){next(error)}});
app.get('/api/reports',auth,async(req,res,next)=>{try{const year=String(req.query.year||new Date().getFullYear()),month=String(req.query.month||'').padStart(2,'0');let filter='user_id=?',params=[req.user.id],period=`January - December ${year}`;if(month&&month!=='00'){filter+=' AND substr(date,1,7)=?';params.push(`${year}-${month}`);period=new Date(`${year}-${month}-01T00:00:00`).toLocaleString('en-US',{month:'long',year:'numeric'})}else{filter+=' AND substr(date,1,4)=?';params.push(year)}const summary=await one(`SELECT SUM(CASE WHEN type='sale' THEN amount ELSE 0 END) revenue,SUM(CASE WHEN type IN ('expense','purchase') THEN amount ELSE 0 END) expenses FROM transactions WHERE ${filter}`,params),revenue=Number(summary.revenue||0),expenses=Number(summary.expenses||0),transactions=await all(`SELECT id,date,description,category,type,amount,reference FROM transactions WHERE ${filter} ORDER BY date DESC,id DESC`,params);res.json({period,summary:{revenue,expenses,profit:revenue-expenses,taxable:Math.max(0,revenue-expenses)},trend:[],breakdown:[],transactions,reports:[{name:'Profit & Loss Statement',period},{name:'Income Statement',period},{name:'Expense Analysis',period},{name:'Cash Flow Report',period}],taxReports:[{name:'Estimated Tax Summary',description:`Taxable income for ${period}`},{name:'Deductible Expenses',description:`Eligible costs for ${period}`} ]})}catch(error){next(error)}});
const frontendPath=path.join(__dirname,'../client/dist');
app.use(express.static(frontendPath));
app.get('*',(req,res,next)=>{const index=path.join(frontendPath,'index.html');if(req.path.startsWith('/api/')||!existsSync(index))return next();res.sendFile(index)});
app.use((error,req,res,next)=>{console.error(error);res.status(500).json({message:'Server error'})});
const port=Number(process.env.PORT||5000);app.listen(port,()=>console.log(`Smart Financial API running on port ${port}`));
